# Boston_housing
* Train : test 비율 70 대 30
* 0:13 인데스를 피쳐값으로 두기
* 13을 label
* LinearRegression을 통해서 accuracy구하기
------------------------------------------------------------
* Train : test = 70:30
* 0:13 => feature값으로하고
* 13 => label
* Feature Scaling 을 한후
* LinearRegression을활용하여 MSE
---------------------------------------------------------------
* Train : test = 70:30
* 0:13 => feature값으로하고
* 13 => label
* random  forest 또는 XGB를 활용하여 적정한 feature_select한후 
* LinearRegression을 활용하여 MSE

In [11]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

In [12]:
boston_house= pd.read_csv('C:/Users/jangd/OneDrive/바탕 화면/python/ml/data_sets/boston_housing.csv')
boston_house

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [13]:
dt_bost_scaler=StandardScaler()
dt_bost_scaler.fit(boston_house)
dt_bost_scaled=dt_bost_scaler.transform(boston_house)

In [14]:
dt_bost_scaled_after=pd.DataFrame(data=dt_bost_scaled,columns=boston_house.columns)

In [15]:
y=dt_bost_scaled_after.iloc[:,-1]
y

0      0.159686
1     -0.101524
2      1.324247
3      1.182758
4      1.487503
         ...
501   -0.014454
502   -0.210362
503    0.148802
504   -0.057989
505   -1.157248
Name: MEDV, Length: 506, dtype: float64

In [16]:
X_features=boston_house.columns
X_features

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')

In [17]:
X=dt_bost_scaled_after.drop(['MEDV'],axis=1)
X

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,-0.419782,0.284830,-1.287909,-0.272599,-0.144217,0.413672,-0.120013,0.140214,-0.982843,-0.666608,-1.459000,0.441052,-1.075562
1,-0.417339,-0.487722,-0.593381,-0.272599,-0.740262,0.194274,0.367166,0.557160,-0.867883,-0.987329,-0.303094,0.441052,-0.492439
2,-0.417342,-0.487722,-0.593381,-0.272599,-0.740262,1.282714,-0.265812,0.557160,-0.867883,-0.987329,-0.303094,0.396427,-1.208727
3,-0.416750,-0.487722,-1.306878,-0.272599,-0.835284,1.016303,-0.809889,1.077737,-0.752922,-1.106115,0.113032,0.416163,-1.361517
4,-0.412482,-0.487722,-1.306878,-0.272599,-0.835284,1.228577,-0.511180,1.077737,-0.752922,-1.106115,0.113032,0.441052,-1.026501
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,-0.413229,-0.487722,0.115738,-0.272599,0.158124,0.439316,0.018673,-0.625796,-0.982843,-0.803212,1.176466,0.387217,-0.418147
502,-0.415249,-0.487722,0.115738,-0.272599,0.158124,-0.234548,0.288933,-0.716639,-0.982843,-0.803212,1.176466,0.441052,-0.500850
503,-0.413447,-0.487722,0.115738,-0.272599,0.158124,0.984960,0.797449,-0.773684,-0.982843,-0.803212,1.176466,0.441052,-0.983048
504,-0.407764,-0.487722,0.115738,-0.272599,0.158124,0.725672,0.736996,-0.668437,-0.982843,-0.803212,1.176466,0.403225,-0.865302
505,-0.415000,-0.487722,0.115738,-0.272599,0.158124,-0.362767,0.434732,-0.613246,-0.982843,-0.803212,1.176466,0.441052,-0.669058

In [18]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.3, random_state=156)
# y_train = y_train.apply(lambda x : round(x)) # 추가 부분
# y_test = y_test.apply(lambda x : round(x))   # 추가 부분

In [21]:
dt_bost_scaled_after.isnull().sum() # 결측치 확인

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [23]:
bost_log=LinearRegression()

In [24]:

bost_log.fit(X_train, y_train) # 타입이 float이라 안됐었음

LinearRegression()

In [25]:
pred=bost_log.predict(X_test)
pred

array([ 0.06763537, -0.31311496,  1.51145275, -0.27925031,  1.07408442,
       -0.5299726 ,  0.84845721, -0.5095132 , -1.27023519, -1.05583527,
       -0.14685462, -0.66615978,  0.66775808,  1.575782  ,  0.09674734,
        0.22162081, -0.86835531, -1.19966893,  0.84295003,  0.10312006,
        0.03584012, -0.53510695, -0.13930387, -0.56973999,  1.25471943,
       -1.66891474, -0.9940695 , -0.33841485, -1.01115216, -1.54539669,
        0.74189332, -1.16402966, -0.29294159,  0.15709885, -0.67362712,
       -1.01469929, -0.89220664, -0.57352658, -0.56180716,  0.14297296,
        1.12171005, -1.43079167, -0.37721578, -2.88650142, -0.28902737,
       -0.13852537,  0.17903233,  1.39599625, -0.24038425,  0.62029989,
        1.10391713,  1.99241144,  2.03073926, -0.29896803,  0.26998305,
        0.17395539, -0.31624352,  1.19292796,  0.11767745, -0.78555367,
        0.01891208,  0.35389154,  0.15938482, -1.49680614, -0.07765706,
        1.86646845,  1.12732975,  0.83493266, -0.88993139,  0.11193865,
       -0.96147985,  1.04899583,  1.51324072,  0.5310868 , -0.11906082,
        0.80677772, -0.1877918 ,  0.46060981,  0.07253318, -0.41393179,
        0.86097296, -0.50164775, -0.27963576,  0.04031444,  0.85158976,
       -0.36908971,  1.33837532,  1.46075278, -0.15764621,  0.61269695,
        1.2463722 , -1.02698748,  0.3591355 ,  0.6294264 ,  0.16998379,
        0.43562534, -0.95212942,  0.54371419,  0.9179572 , -0.04123881,
        0.54329292, -0.1751621 , -1.12448822, -0.61658958,  0.07120056,
        0.29812808,  0.25502818,  0.76506206, -0.88591515,  0.1319362 ,
        0.05185826,  0.55107734, -0.85911481, -0.28799665, -0.19138306,
        1.5367375 ,  0.19723735, -1.25512944, -0.50878799,  1.02755806,
        1.01686325,  0.05658179,  0.53738072,  1.27163261, -0.11681259,
        0.34829252, -1.49157245, -0.66176249,  0.21862845,  0.89106317,
       -0.19035876, -0.35220821,  1.35271347, -0.17152672,  1.46437673,
       -0.01089475, -0.33578799, -0.44868358, -0.37228952,  0.13823885,
        0.07006054, -0.34688084, -0.84880178, -0.74546827,  1.42790701,
       -0.15837202,  0.78122385, -0.15582889,  0.22019107,  0.16988895,
       -0.44122471,  1.01224782])

In [26]:
y_test

210   -0.090641
15    -0.286548
264    1.520154
396   -1.091945
234    0.703873
         ...
393   -0.950457
325    0.224988
53     0.094383
401   -1.668784
178    0.801827
Name: MEDV, Length: 152, dtype: float64

In [27]:
# accuracy_score(y_test,pred) # classification에서만 사용됨 따라서 linear에서는 score함수 사용해줘야함
dt_bost_accuracy=bost_log.score(X_train,y_train)
dt_bost_accuracy_test=bost_log.score(X_test,y_test)

In [28]:
print(f'훈련데이터 정확도 : {dt_bost_accuracy}\n테스트데이터 정확도 : {dt_bost_accuracy_test}')

훈련데이터 정확도 : 0.7273505005599823
테스트데이터 정확도 : 0.757226332313894

In [29]:
pred=bost_log.predict(X_test)

In [31]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
mse= mean_squared_error(y_test,pred)

mae=mean_absolute_error(y_test,pred)

In [32]:
print(f'MSE 값:{mse}\n MAE 값:{mae}')

MSE 값:0.20489228675764298
 MAE 값:0.34976755615593225