# Boston_housing
* Train : test 비율 70 대 30
* 0:13 인데스를 피쳐값으로 두기
* 13을 label
* LinearRegression을 통해서 accuracy구하기
------------------------------------------------------------
* Train : test = 70:30
* 0:13 => feature값으로하고
* 13 => label
* Feature Scaling 을 한후
* LinearRegression을활용하여 MSE
---------------------------------------------------------------
* Train : test = 70:30
* 0:13 => feature값으로하고
* 13 => label
* random  forest 또는 XGB를 활용하여 적정한 feature_select한후 
* LinearRegression을 활용하여 MSE

In [4]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler

In [5]:
boston_house= pd.read_csv('C:/Users/jangd/OneDrive/바탕 화면/python/ml/data_sets/boston_housing.csv')
boston_house

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [6]:
dt_bost_scaler=MinMaxScaler()
dt_bost_scaler.fit(boston_house)
dt_bost_scaled=dt_bost_scaler.transform(boston_house)

In [7]:
dt_bost_scaled_after=pd.DataFrame(data=dt_bost_scaled,columns=boston_house.columns)

In [8]:
y=dt_bost_scaled_after.iloc[:,-1]
y

0      0.422222
1      0.368889
2      0.660000
3      0.631111
4      0.693333
         ...
501    0.386667
502    0.346667
503    0.420000
504    0.377778
505    0.153333
Name: MEDV, Length: 506, dtype: float64

In [9]:
X_features=boston_house.columns
X_features

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')

In [10]:
X=dt_bost_scaled_after.drop(['MEDV'],axis=1)
X

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.000000,0.18,0.067815,0.0,0.314815,0.577505,0.641607,0.269203,0.000000,0.208015,0.287234,1.000000,0.089680
1,0.000236,0.00,0.242302,0.0,0.172840,0.547998,0.782698,0.348962,0.043478,0.104962,0.553191,1.000000,0.204470
2,0.000236,0.00,0.242302,0.0,0.172840,0.694386,0.599382,0.348962,0.043478,0.104962,0.553191,0.989737,0.063466
3,0.000293,0.00,0.063050,0.0,0.150206,0.658555,0.441813,0.448545,0.086957,0.066794,0.648936,0.994276,0.033389
4,0.000705,0.00,0.063050,0.0,0.150206,0.687105,0.528321,0.448545,0.086957,0.066794,0.648936,1.000000,0.099338
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.000633,0.00,0.420455,0.0,0.386831,0.580954,0.681771,0.122671,0.000000,0.164122,0.893617,0.987619,0.219095
502,0.000438,0.00,0.420455,0.0,0.386831,0.490324,0.760041,0.105293,0.000000,0.164122,0.893617,1.000000,0.202815
503,0.000612,0.00,0.420455,0.0,0.386831,0.654340,0.907312,0.094381,0.000000,0.164122,0.893617,1.000000,0.107892
504,0.001161,0.00,0.420455,0.0,0.386831,0.619467,0.889804,0.114514,0.000000,0.164122,0.893617,0.991301,0.131071
505,0.000462,0.00,0.420455,0.0,0.386831,0.473079,0.802266,0.125072,0.000000,0.164122,0.893617,1.000000,0.169702

In [11]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.3, random_state=156)
# y_train = y_train.apply(lambda x : round(x)) # 추가 부분
# y_test = y_test.apply(lambda x : round(x))   # 추가 부분

In [12]:
dt_bost_scaled_after.isnull().sum() # 결측치 확인

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [13]:
bost_log=LinearRegression()

In [14]:

bost_log.fit(X_train, y_train) # 타입이 float이라 안됐었음

LinearRegression()

In [15]:
pred=bost_log.predict(X_test)
pred

array([ 0.40342757,  0.32568672,  0.69822337,  0.33260114,  0.60892236,
        0.28140915,  0.56285424,  0.28558652,  0.13026379,  0.17403955,
        0.35963343,  0.25360272,  0.52595945,  0.71135799,  0.4093716 ,
        0.43486802,  0.21231884,  0.14467187,  0.5617298 ,  0.41067277,
        0.39693568,  0.28036083,  0.36117513,  0.27328953,  0.64580406,
        0.04886219,  0.18665076,  0.32052104,  0.18316286,  0.07408186,
        0.54109624,  0.15194863,  0.32980568,  0.42169405,  0.25207806,
        0.18243861,  0.20744892,  0.27251639,  0.27490924,  0.41880986,
        0.61864647,  0.09748169,  0.31259874, -0.19974227,  0.33060488,
        0.36133408,  0.42617239,  0.67464969,  0.34053673,  0.51626953,
        0.61501355,  0.79642457,  0.80425027,  0.32857521,  0.44474253,
        0.42513579,  0.32504794,  0.6331876 ,  0.41364507,  0.22922511,
        0.39347935,  0.4618748 ,  0.4221608 ,  0.08400298,  0.37376205,
        0.77070978,  0.61979389,  0.56009283,  0.20791348,  0.41247333,
        0.19330485,  0.60379982,  0.69858843,  0.49805418,  0.36530831,
        0.55434421,  0.35127496,  0.48366432,  0.4044276 ,  0.30510214,
        0.56540968,  0.28719247,  0.33252244,  0.39784924,  0.56349384,
        0.31425791,  0.66288476,  0.68787155,  0.35743003,  0.51471718,
        0.64409974,  0.17992963,  0.4629455 ,  0.51813296,  0.42432487,
        0.47856304,  0.195214  ,  0.50063241,  0.57704462,  0.38119786,
        0.5005464 ,  0.35385366,  0.16002212,  0.26372387,  0.40415551,
        0.45048912,  0.44168907,  0.54582679,  0.20873351,  0.41655639,
        0.40020624,  0.50213581,  0.21420554,  0.33081533,  0.3505417 ,
        0.70338596,  0.42988945,  0.13334806,  0.28573459,  0.5994227 ,
        0.59723906,  0.40117068,  0.49933926,  0.64925736,  0.36576735,
        0.4607316 ,  0.08507159,  0.25450055,  0.43425705,  0.57155344,
        0.35075084,  0.31770474,  0.6658123 ,  0.35459593,  0.68861148,
        0.38739345,  0.32105739,  0.29800659,  0.31360458,  0.41784325,
        0.40392274,  0.31879247,  0.21631124,  0.23740967,  0.68116516,
        0.35728183,  0.54912667,  0.35780108,  0.4345761 ,  0.42430551,
        0.29952952,  0.59629669])

In [16]:
y_test

210    0.371111
15     0.331111
264    0.700000
396    0.166667
234    0.533333
         ...
393    0.195556
325    0.435556
53     0.408889
401    0.048889
178    0.553333
Name: MEDV, Length: 152, dtype: float64

In [17]:
# accuracy_score(y_test,pred) # classification에서만 사용됨 따라서 linear에서는 score함수 사용해줘야함
dt_bost_accuracy=bost_log.score(X_train,y_train)
dt_bost_accuracy_test=bost_log.score(X_test,y_test)

In [18]:
print(f'훈련데이터 정확도 : {dt_bost_accuracy}\n테스트데이터 정확도 : {dt_bost_accuracy_test}')

훈련데이터 정확도 : 0.7273505005599823
테스트데이터 정확도 : 0.7572263323138942

In [19]:
pred=bost_log.predict(X_test)

In [20]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
mse= mean_squared_error(y_test,pred)

mae=mean_absolute_error(y_test,pred)

In [21]:
print(f'MSE 값:{mse}\n MAE 값:{mae}')

MSE 값:0.008541686868099752
 MAE 값:0.07141485209165437